### ISSUE TITLE
Configured Waze region (US) is not valid

### ISSUE THREAD

**Issue by jackyaz** [rodpayne/home-assistant_person_location#12]
I keep seeing the below error in my logs, it's persisted across multiple versions of HA, the most recent being 2023.12.0

Do I need to amend configuration or is it safe to ignore?

```Logger: custom_components.person_location.const
Source: custom_components/person_location/const.py:264
Integration: Person Location ([documentation](https://github.com/rodpayne/home-assistant_person_location/blob/master/README.md#table-of-contents), [issues](https://github.com/rodpayne/home-assistant_person_location/issues))
First occurred: 11:56:26 (1 occurrences)
Last logged: 11:56:26

Configured Waze region (US) is not valid```

**Comment by rodpayne** [comment]
What version of Person Location are you running?  `Settings` -> `System` -> `Repairs` -> `System Information` in the overflow menu (top right three dots).  This was fixed in 874ab85 because the Waze integration requires the WAZE region to be lowercase.

**Comment by rodpayne** [comment]
I see that I had neglected to make a new release because the Hassfest test was not passing.  I have just added version 2023.09.26.  Please give it a try, it should automatically change Waze region to lowercase.

**Comment by jackyaz** [comment]
The original error is gone, but now I see:

Waze Exception TypeError: WazeRouteCalculator.__init__() got an unexpected keyword argument 'avoid_toll_roads'

**Comment by rodpayne** [comment]
I am checking it out...  Is this still with Waze region "us"?  What version of Home Assistant are you running?  (I am on 2023.11.3 and I am not seeing it in the system log.)  Does it happen immediately after startup, or is it later when you are away somewhere?  (I suspect it happens when you are away and that is why I don't see it yet... I am homebound right now.)

It seems odd that this option would be removed from the Waze route calculator, but maybe it has been renamed or something.    The avoid_toll_roads isn't a critical option for my needs, so I suppose that removing it would be the quickest fix.

**Comment by rodpayne** [comment]
If you have coding ability, you could try removing line 800 of `config\custom_components\person_location\reverse_geocode.py`, which has: `avoid_toll_roads=True,`.

**Comment by rodpayne** [comment]
Release Version 2023.12.09 should fix this issue.

**Comment by jackyaz** [comment]
I'll try it out, thanks!

**Comment by jackyaz** [comment]
Seems fixed!
