### ISSUE TITLE
Setup question ...

### ISSUE THREAD

**Issue by swa72** [rodpayne/home-assistant_person_location#4]
I'm still confused after setup (Home Assistant Core 2022.5.3). Installation with HACS went smooth and I found a bunch of `sensors.<devicename>_geocoded_location`  entries afterwards. I assume, they were created by this integration, right?

I read "This custom integration will look at all device trackers that are for a particular person and combine them into a single person location sensor, sensor.<name>_location. " 

First question: how does the integration determine a mapping from device to person?  Is the source the same as going to Settings | People | <MyName> and add devices under "Select the devices that belong to this person."?

I also noticed that I cannot change all config parameters in the GUI as described in the README.  Going to Settings | Devices & Services and clicking on "Home Person Location" and "Configure" I can only change Hours Extended Away, Minutes Just Arrived and Minutes Just Left. All others like "Google Region" are no longer accessible.

**Comment by rodpayne** [comment]
1) The person and their associated devices can be specified in two ways. 

The `configuration.yaml` can list the people to have output sensors created:
```
# Example configuration.yaml entry
person_location:
  person_names:
    - name: Rod
      devices:
        - device_tracker.rod_iphone
        - device_tracker.rod_iphone_3
        - sensor.ford_focus_location
    - name: Pam
      devices: person.pam
```
In this example, `sensor.rod_location` will reflect changes detected in three devices; `sensor.pam_location` will reflect changes in the `person.pam` entity.

The second way to identify the person would only apply if there is an automation that is calling the `person_location.process_trigger` service.  The person is identified from the triggered device tracker by looking for a customized attribute in the device tracker of `person_name`, `account_name`, or `owner_fullname`.  As a last resort, it will try to extract the person's name from the triggered device tracker's `entity_id`.  

2) Right now the configuration update is a little quirky in that changes to the basic configuration can be done by going to the Integrations page, selecting `+ ADD INTEGRATION`, and following the procedure as if you are adding it for the first time.  The previous answers will be filled in by default and when submitted they will update the integration.  

I will keep this issue open to remind me to:
1) Update the configuration flow to define the `person_names` configuration that is only in the YAML configuration.
2) Update the configuration update flow so that all parameters can be updated.

**Comment by swa72** [comment]
Thanks for commenting.

**Comment by rodpayne** [comment]
Version 2023.01.23 is adding the `person_names`/`devices` configuration to the options configuration update flow (in addition to keeping the yaml option available).
